### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by ajthechan** [MengTo/Spring#57] opened 2015-04-09 19:14 UTC
Didn't have this problem last night. Not sure what cause this? Help, please.

/Spring-master/Spring/LoadingView.swift
/Spring-master/Spring/LoadingView.swift:40:99: 'AnyObject' is not convertible to 'UIView'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/Misc.swift
/Spring-master/Spring/Misc.swift:26:37: 'countElements' has been renamed to count
/Spring-master/Spring/Misc.swift:75:21: 'countElements' has been renamed to count
/Spring-master/Spring/DesignableTabBarController.swift
/Spring-master/Spring/DesignableTabBarController.swift:36:35: 'selectedImageTintColor' was deprecated in iOS version 8.0: Use tintColor
/Spring-master/Spring/DesignableTabBarController.swift:49:46: '?' must be followed by a call, member lookup, or subscript
/Spring-master/Spring/DesignableTabBarController.swift:50:53: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/DesignableTabBarController.swift:58:47: '?' must be followed by a call, member lookup, or subscript
/Spring-master/Spring/DesignableTabBarController.swift:59:53: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/DesignableTabBarController.swift:67:46: '?' must be followed by a call, member lookup, or subscript
/Spring-master/Spring/DesignableTabBarController.swift:68:53: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/DesignableTabBarController.swift:76:47: '?' must be followed by a call, member lookup, or subscript
/Spring-master/Spring/DesignableTabBarController.swift:77:53: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/DesignableTabBarController.swift:85:46: '?' must be followed by a call, member lookup, or subscript
/Spring-master/Spring/DesignableTabBarController.swift:86:53: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/DesignableTabBarController.swift:95:39: '[AnyObject]?' is not convertible to '[UITabBarItem]'; did you mean to use 'as!' to force downcast?
/Spring-master/Spring/Spring.swift
/Spring-master/Spring/Spring.swift:450:35: Missing argument label 'completion:' in call

**Comment by ajthechan** [comment] 2015-04-09 20:13
Fixed. Found on answer on Facebook group:)

**Comment by Epick362** [comment] 2015-04-09 20:29
Was this caused by the new Swift version?

**Comment by ajthechan** [comment] 2015-04-09 20:31
Seem to be so.

**Comment by adamnbowen** [comment] 2015-04-09 21:13
There are several unmerged pull requests that would fix this issue.  This is caused by the update to Swift 1.2

**Comment by jamztang** [comment] 2015-04-10 11:19
#48 was merged earlier, the drop in method shall already fix the issue. We'll be putting up for Cocoapods soon.

**Closed by jamztang** 2015-04-10 11:19 UTC

**Comment by JCombe** [comment] 2015-06-01 02:51
@ajthechan I have the same issue with my app... could you tell me the name of the Facebook group which helped you with it.

**Comment by ajthechan** [comment] 2015-06-01 12:14
https://www.facebook.com/groups/designcode/1577045382558585/?notif_t=group_activity
