### ISSUE TITLE
Use enum for keys, not plain strings

### ISSUE THREAD

**Issue by edekhayser** [MengTo/Spring#51] opened 2015-04-05 19:54 UTC
Using these magic keywords is not very extensible or easy to use. Having predefined constants would be a step up, but you can even do better with an enum for all the animation options. If you wanted, you could use these strings to define the enum values in the inner workings not to break the current code.

**Comment by MengTo** [comment] 2015-04-06 05:54
I agree, we'll think of something.

**Comment by schneiderandre** [comment] 2015-04-06 18:16
It seems that this is a duplicate of #22. @edekhayser If you agree, we can close this issue and continue the discussion there.

**Closed** 2015-04-06 18:27 UTC
