### ISSUE TITLE
cornerRadius property override error

### ISSUE THREAD

**Issue by giacomopiva** [MengTo/Spring#64] opened 2015-04-15 14:25 UTC
I'm getting an error on the cornerRadius property declaration: "Overriding declaration requires an 'override' keyword"

    @IBInspectable public var cornerRadius: CGFloat = 0 {
        didSet {
            layer.cornerRadius = cornerRadius
        }
    }

Anyone is getting the same eerror with iOS 8.3 SDK ?

It is possible to fix by replacing the declaration with:
    @IBInspectable public override var cornerRadius: CGFloat  {
        didSet {
            layer.cornerRadius = cornerRadius
        }
    }

Note that the compiler complains also about the initialization value.

**Comment by yume190** [comment] 2015-04-15 14:37
You have two choice:
1. optional var  

    cornerRadius: CGFloat?
    // or
    cornerRadius: CGFloat!

2. non optional var must have initial value

    cornerRadius: CGFloat = 0
    // or 
    init(){
        cornerRadius = 0
        super.init()
    }

**Comment by schneiderandre** [comment] 2015-07-15 14:35
I'm not able to reproduce the compiler error in Xcode 6.4 and iOS 8.4.

@giacomopiva If this problem has now been solved, we can close the issue.

**Comment by giacomopiva** [comment] 2015-07-16 08:41
I did download a fresh copy from master and I test it on a new project with SDK 8.4 and Xcode 6.4 and I didn’t get the error again.

**Comment by schneiderandre** [comment] 2015-07-16 08:45
Great! Thank's for your feedback! :+1:

**Closed by schneiderandre** 2015-07-16 08:45 UTC
